"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowUpRight, CheckCircle2, ChevronRight, CircleHelp, Moon, RefreshCw, Sun, Upload, X } from "lucide-react";

type Customer = { customer_id:string; name:string; plan:string; monthly_value:number; satisfaction_score?:number; support_tickets_30d:number; usage_change_pct:number; payment_failed:boolean; transcript:string };
type Result = { customer:Customer; risk_score:number; risk_level:"Critical"|"High"|"Watch"|"Healthy"; signals:string[]; reasons:string[]; rationale:string; recommended_action:string };
type Summary = { total?:number; critical?:number; high?:number; watch?:number; healthy?:number; revenue_at_risk?:number };
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
const levels = ["Critical", "High", "Watch", "Healthy"] as const;
const levelColor = { Critical:"#fb7185", High:"#f59e0b", Watch:"#8b5cf6", Healthy:"#22c55e" };

function Status({ level }:{level:string}) { return <span className={`pill ${level.toLowerCase()}`}>{level}</span>; }
function ThemeToggle({ dark, onToggle }:{dark:boolean;onToggle:()=>void}) { return <button onClick={onToggle} className="icon-button" aria-label="Toggle colour mode">{dark ? <Sun size={17}/> : <Moon size={17}/>}</button>; }
function RiskDistribution({ summary }:{summary:Summary}) {
  const total = Math.max(summary.total || 0, 1); const data = levels.map(level => ({level, value:summary[level.toLowerCase() as keyof Summary] as number || 0})); let offset=0;
  return <div className="chart-card"><div className="chart-heading"><div><p className="eyebrow">Portfolio health</p><h2>Risk distribution</h2></div><span className="chart-note">{summary.total || 0} accounts</span></div><div className="donut-layout"><svg viewBox="0 0 42 42" className="donut" role="img" aria-label="Customer risk distribution">{data.map(item=>{const pct=item.value/total*100;const circle=<circle key={item.level} cx="21" cy="21" r="15.9155" fill="transparent" stroke={levelColor[item.level]} strokeWidth="4.5" strokeDasharray={`${pct} ${100-pct}`} strokeDashoffset={-offset} className="donut-segment"/>;offset+=pct;return circle;})}</svg><div className="donut-center"><b>{summary.total ?? "—"}</b><span>accounts</span></div><div className="legend">{data.map(item=><div key={item.level}><i style={{background:levelColor[item.level]}}/><span>{item.level}</span><b>{item.value}</b></div>)}</div></div></div>;
}
function SignalChart({ results }:{results:Result[]}) {
  const items = [...results].sort((a,b)=>b.risk_score-a.risk_score).slice(0,6); const max = Math.max(...items.map(item=>item.risk_score), 1);
  return <div className="chart-card"><div className="chart-heading"><div><p className="eyebrow">Immediate action</p><h2>Highest-risk accounts</h2></div><span className="chart-note">score / 100</span></div><div className="bar-chart">{items.length?items.map(item=><div className="bar-row" key={item.customer.customer_id}><div className="bar-label"><span>{item.customer.name}</span><b>{item.risk_score}</b></div><div className="bar-track"><div className="bar-fill" style={{width:`${item.risk_score/max*100}%`, background:levelColor[item.risk_level]}}/></div></div>):<div className="empty-chart">Load a dataset to view risk signals.</div>}</div></div>;
}
function Metric({label,value,note,accent="default"}:{label:string;value:string|number;note:string;accent?:string}) { return <div className="metric-card"><div className="metric-label">{label}</div><div className={`metric-value ${accent}`}>{value}</div><div className="metric-note">{note}</div></div>; }

export default function Home() {
  const [results,setResults]=useState<Result[]>([]); const [summary,setSummary]=useState<Summary>({}); const [selected,setSelected]=useState<Result|null>(null);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [showInput,setShowInput]=useState(false); const [raw,setRaw]=useState(""); const [filter,setFilter]=useState("All"); const [dark,setDark]=useState(false);
  useEffect(()=>{const saved=localStorage.getItem("signal-theme");const prefers=window.matchMedia("(prefers-color-scheme: dark)").matches;setDark(saved ? saved === "dark" : prefers);},[]);
  useEffect(()=>{document.documentElement.classList.toggle("dark",dark);localStorage.setItem("signal-theme",dark?"dark":"light");},[dark]);
  async function load(path="/api/sample-analysis", init?:RequestInit) { setLoading(true); setError(""); try { const response=await fetch(`${API}${path}`,init); const data=await response.json(); if(!response.ok) throw new Error(data.detail || "Analysis failed"); setResults(data.results); setSummary(data.summary); setSelected(data.results[0]||null); } catch(error:any) { setError(`${error.message}. Is FastAPI running on port 8000?`); } finally { setLoading(false); } }
  useEffect(()=>{load();},[]);
  const visible=useMemo(()=>filter === "All" ? results : results.filter(item=>item.risk_level===filter),[results,filter]);
  function runCustom(){try{const customers=JSON.parse(raw);load("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customers})});setShowInput(false);}catch{setError("Paste a valid JSON array of customer records.");}}
  return <main className="app-shell"><header className="topbar"><div className="topbar-inner"><div className="brand"><div className="brand-mark"><Activity size={18}/></div><div><div className="brand-name">Signal<span>Detector</span></div><div className="brand-subtitle">Customer operations intelligence</div></div></div><div className="header-actions"><div className="live-status"><i/> Monitoring active</div><ThemeToggle dark={dark} onToggle={()=>setDark(value=>!value)}/><button onClick={()=>setShowInput(value=>!value)} className="button secondary"><Upload size={14}/> Test data</button><button onClick={()=>load()} className="button primary"><RefreshCw size={14}/> Refresh</button></div></div></header>
    <div className="page"><section className="hero"><div><p className="eyebrow accent">Customer signal intelligence</p><h1>Know who needs attention <em>before they churn.</em></h1><p className="hero-copy">A prioritised view of early warning signals across satisfaction, support, billing and adoption.</p></div><div className="hero-insight"><div className="insight-icon"><AlertTriangle size={17}/></div><div><span>Current focus</span><strong>{summary.critical || 0} critical accounts</strong><small>Intervene within 24 hours</small></div><ArrowUpRight size={18}/></div></section>
      {showInput && <section className="input-panel"><div className="input-title"><div><p className="eyebrow">Sandbox</p><h2>Run a custom data test</h2></div><button className="close-button" onClick={()=>setShowInput(false)}><X size={17}/></button></div><p>Paste a JSON array using the documented customer schema. It stays in this session and is not stored.</p><textarea value={raw} onChange={event=>setRaw(event.target.value)} placeholder='[{"customer_id":"CUS-1","name":"Example Co", ...}]' className="mono"/><button onClick={runCustom} className="button primary">Analyse customer data <ArrowUpRight size={14}/></button></section>}
      {error && <div className="error-box">{error}</div>}
      <section className="metric-grid"><Metric label="Customers monitored" value={summary.total ?? "—"} note="in the selected dataset"/><Metric label="Critical attention" value={summary.critical ?? "—"} note="action within 24 hours" accent="danger"/><Metric label="Revenue at risk" value={summary.revenue_at_risk ? `$${(summary.revenue_at_risk/1000).toFixed(1)}k` : "—"} note="monthly recurring value" accent="warning"/><Metric label="Healthy accounts" value={summary.healthy ?? "—"} note="no material warning signals" accent="success"/></section>
      <section className="charts-grid"><RiskDistribution summary={summary}/><SignalChart results={results}/></section>
      <section className="workspace"><div className="queue card"><div className="section-head"><div><p className="eyebrow">Operations queue</p><h2>Prioritised attention list</h2><p>Accounts ranked by combined signal strength and recurring value.</p></div><div className="filter-tabs">{["All",...levels].map(value=><button key={value} onClick={()=>setFilter(value)} className={filter===value?"active":""}>{value}</button>)}</div></div>{loading?<div className="loading">Analysing customer signals<span>.</span><span>.</span><span>.</span></div>:<div className="queue-list">{visible.map(item=><button key={item.customer.customer_id} onClick={()=>setSelected(item)} className={`queue-row ${selected?.customer.customer_id===item.customer.customer_id?"selected":""}`}><div className="avatar">{item.customer.name.split(" ").map(part=>part[0]).join("").slice(0,2)}</div><div className="account"><div><strong>{item.customer.name}</strong><Status level={item.risk_level}/></div><span>{item.customer.plan} <i>·</i> {item.signals.slice(0,2).join(" · ") || "No active signals"}</span></div><div className="risk-number"><b>{item.risk_score}</b><span>/100</span></div><ChevronRight size={17}/></button>)}{!visible.length&&<div className="empty">No accounts match this filter.</div>}</div>}</div>
        <aside className="detail card">{selected?<><div className="detail-header"><div><p className="mono">{selected.customer.customer_id}</p><h2>{selected.customer.name}</h2><span>{selected.customer.plan} · ${selected.customer.monthly_value.toLocaleString()} MRR</span></div><Status level={selected.risk_level}/></div><div className="score-row"><div className="score-ring" style={{background:`conic-gradient(${levelColor[selected.risk_level]} ${selected.risk_score*3.6}deg, var(--ring-track) 0deg)`}}><div><b>{selected.risk_score}</b><span>risk</span></div></div><div><p className="eyebrow">AI signal summary</p><p className="rationale">{selected.rationale}</p></div></div><div className="signal-section"><p className="eyebrow">Detected signals</p><div className="signal-chips">{selected.signals.length?selected.signals.map(signal=><span key={signal}>{signal}</span>):<span>No material signals</span>}</div></div><div className="recommendation"><div><ArrowUpRight size={15}/><span>Recommended next action</span></div><p>{selected.recommended_action}</p></div><div className="evidence"><p className="eyebrow">Evidence</p>{selected.reasons.length?selected.reasons.map(reason=><div key={reason}><i/> {reason}</div>):<span>No material warning evidence.</span>}</div></>:<div className="empty-detail"><CircleHelp size={24}/><p>Select an account to review its signal evidence.</p></div>}</aside></section>
      <footer><CheckCircle2 size={14}/> Explainable scoring active <span>·</span> LLM enrichment is optional and configured server-side.</footer>
    </div></main>;
}
